const mongoose=require('mongoose')
var surgery_appointmentSchema=new mongoose.Schema({
    appointment_id:{
        type:'String'
    },
    patient_id:{
        type:'String'
    },
    patient_name:{
        type:'String'
    },
    doctor_id:{
        type:'String'
    },
    doctor_name:{
        type:'String'
    },
    rm_id:{
        type:'String'
    },
    status:{
        type:Boolean,default:false
    },
    doctors_surgery:[{
        doctor_id:{
            type:'String'
        },
        doctor_name:{
            type:'String'
        }
    }],
    equipment_used:[{
        name:{
            type:'String'
        },
        equipment_id:{
            type:'String'
        }
    }],
    nurses:[{
        nurse_id:{
            type:'String'
        },
        nurse_name:{
            type:'String'
        }
    }],
    surgery_done_status:{
        type:Boolean,default:false
    },
    superadmin_approval:{
        type:Boolean,default:false
    }
})
var surgery_appointmentModel=mongoose.model("surgery_appointment",surgery_appointmentSchema)
module.exports=surgery_appointmentModel